version: "3.8"

x-common-variables: &common-variables
  API_HOST: ${API_HOST}
  DB_USER: ${DB_USER}
  DB_PASS: ${DB_PASS}
  DB_HOST: ${DB_HOST}
  DB_NAME: ${DB_NAME}
  DB_PORT: ${DB_PORT:-5432}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
  SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
  #SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
  #SLACK_CLIENT_SECRET: ${SLACK_SECRET}
  OMO_CUSTOMER_NAMESPACE: ${OMO_CUSTOMER_NAMESPACE}
  ATLASSIAN_SPACE_KEY: ${ATLASSIAN_SPACE_KEY}
  ATLASSIAN_USERNAME: ${ATLASSIAN_USERNAME}
  ATLASSIAN_API_TOKEN: ${ATLASSIAN_API_TOKEN}
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  PINECONE_INDEX: ${PINECONE_INDEX}
  PINECONE_API_KEY: ${PINECONE_API_KEY}
  PINECONE_ENV: ${PINECONE_ENV}

volumes:
  pg_sandbox_data:
  pg_development_data:
#  chroma_index_data:

#networks:
#  net:
#    driver: bridge

services:
  db:
    image: postgres:16.0-bullseye
    volumes:
      - ./omo_api/db/init:/docker-entrypoint-initdb.d
      - "pg_${APP_ENV}_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment: *common-variables

  server:
    build: ./omo_api
    platform: linux/amd64
    ports:
      - 8000:80
    volumes:
      - ./omo_api:/var/www/omo_api
    environment:
      <<: *common-variables
      PYTHONPATH: "$${PYTHONPATH}:/var/www" # for absolute imports
      PORT: 8000
    depends_on:
      - db
  
  websockets:
    build: ./omo_ws
    platform: linux/amd64
    ports:
      - 8001:80
    volumes:
      - ./omo_ws:/var/www/omo_ws
    environment:
      <<: *common-variables
      PYTHONPATH: "$${PYTHONPATH}:/var/www" # for absolute imports
      PORT: 8001
    depends_on:
      - server
  
  # chromadb:
  #   image: chromadb/chroma:0.4.17
  #   volumes:
  #     - chroma_index_data:/chroma/.chroma/index
  #   ports:
  #     - 8002:8000
    