version: "3.8"

volumes:
  pg_sandbox_data:
  pg_development_data:

services:
  db:
    image: postgres:16.0-bullseye
    hostname: omo_db_1
    container_name: omo_db_1
    volumes:
      - ./omo_api/db/init:/docker-entrypoint-initdb.d
      - "pg_${APP_ENV}_data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    env_file:
      - ./omo_api/conf/envs/.env.development
    environment:
      APP_ENV: development

  server:
    hostname: omo_server_1
    container_name: omo_server_1
    build:
      context: ./omo_api
      dockerfile: Dockerfile.local
    platform: linux/amd64
    ports:
      - 8000:80
    volumes:
      - ./omo_api:/var/www/omo_api
    env_file:
      - ./omo_api/conf/envs/.env.development
      - "./omo_api/conf/envs/${CUSTOMER_ENV}/.env"
    environment:
      PYTHONPATH: "$${PYTHONPATH}:/var/www" # for absolute imports
      PORT: 8000
    depends_on:
      - db
  
  websockets:
    hostname: omo_ws_1
    container_name: omo_ws_1
    # profiles:
    #   - donotstart # comment out if you want to start this service
    build:
      context: ./omo_ws
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 8001:80
    volumes:
      - ./omo_ws:/var/www/omo_ws
      - ./omo_api:/var/www/omo_api
    env_file:
      - ./omo_ws/conf/envs/.env.development
    environment:
      PYTHONPATH: "$${PYTHONPATH}:/var/www" # for absolute imports
      PORT: 8001
    depends_on:
      - server
  