connectors:
  googledrive:
    display_name: 'Google Drive'
    enabled: true
  notion:
    display_name: 'Notion'
    enabled: true
  confluence:
    display_name: 'Confluence'
    enabled: false

vector_stores:
  pinecone:
    display_name: 'Pinecone'
    enabled: true