FROM debian:bookworm

RUN apt-get update
RUN python3-pip
#RUN apt-get -y install tesseract-ocr libcairo2-dev pkg-config python3-dev python3-pip
WORKDIR /var/www/omo
COPY . /var/www/omo/

ENV PYTHONPATH "${PYTHONPATH}:/var/www/"

CMD pip install --no-cache-dir -r /var/www/omo/requirements.txt

#CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]