drop table confluenceobject;
drop table confluencespacekey;
drop table gdriveobject;
drop table googledriveconfig;
drop table atlassianconfig;
drop table pineconeconfig;
drop table teamconfig;
drop table users;
drop table team;