"""add slack_team_id to User

Revision ID: 13a3d0fa557a
Revises: 8fe556082641
Create Date: 2024-01-02 06:02:51.904811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a3d0fa557a'
down_revision: Union[str, None] = '8fe556082641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('slack_team_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'slack_team_id')
    # ### end Alembic commands ###
