"""change last_edited_utc to tiemstamp column from bigint

Revision ID: b0eec74e32be
Revises: 
Create Date: 2023-12-21 06:13:42.789790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0eec74e32be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gdriveobject', sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('gdriveobject', 'last_edited_utc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gdriveobject', sa.Column('last_edited_utc', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('gdriveobject', 'last_edited_at')
    # ### end Alembic commands ###
