"""convert to jsonb type

Revision ID: bd035f848ee7
Revises: da6923d86c34
Create Date: 2024-04-13 17:26:50.743102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd035f848ee7'
down_revision: Union[str, None] = 'da6923d86c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('teamconfig')
    op.alter_column('googledriveconfig', 'files',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('googledriveconfig', 'files',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # op.create_table('teamconfig',
    # sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='teamconfig_team_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='teamconfig_pkey')
    # )
    # ### end Alembic commands ###
