"""usercelerytasks table

Revision ID: cf7f4249cc31
Revises: bd035f848ee7
Create Date: 2024-04-18 06:22:28.797106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'cf7f4249cc31'
down_revision: Union[str, None] = 'bd035f848ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

# The table was created when running 'alembic revision'. we did
# not have to run `alembic upgrade``
# This is essentially a no-op - this file was created when autogenerating
# Just ensure the table exists in pg.
# CREATE TABLE usercelerytasks (
# 	job_id VARCHAR NOT NULL,
# 	user_id INTEGER NOT NULL,
# 	id SERIAL NOT NULL,
# 	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
# 	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
# 	PRIMARY KEY (id),
# 	FOREIGN KEY(user_id) REFERENCES users (id)
# )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
