"""remove teamconfig to simplify relationships

Revision ID: da6923d86c34
Revises: 337f1dc63067
Create Date: 2024-04-13 13:43:09.508438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da6923d86c34'
down_revision: Union[str, None] = '337f1dc63067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atlassianconfig', sa.Column('team_id', sa.Integer(), nullable=True))
    op.drop_constraint('atlassianconfig_team_config_id_fkey', 'atlassianconfig', type_='foreignkey')
    op.create_foreign_key(None, 'atlassianconfig', 'team', ['team_id'], ['id'])
    op.drop_column('atlassianconfig', 'team_config_id')
    op.add_column('googledriveconfig', sa.Column('team_id', sa.Integer(), nullable=True))
    op.drop_constraint('googledriveconfig_team_config_id_fkey', 'googledriveconfig', type_='foreignkey')
    op.create_foreign_key(None, 'googledriveconfig', 'team', ['team_id'], ['id'])
    op.drop_column('googledriveconfig', 'team_config_id')
    op.add_column('pineconeconfig', sa.Column('team_id', sa.Integer(), nullable=True))
    op.drop_constraint('pineconeconfig_team_config_id_fkey', 'pineconeconfig', type_='foreignkey')
    op.create_foreign_key(None, 'pineconeconfig', 'team', ['team_id'], ['id'])
    op.drop_column('pineconeconfig', 'team_config_id')
    op.drop_table('teamconfig')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pineconeconfig', sa.Column('team_config_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pineconeconfig', type_='foreignkey')
    op.create_foreign_key('pineconeconfig_team_config_id_fkey', 'pineconeconfig', 'teamconfig', ['team_config_id'], ['id'])
    op.drop_column('pineconeconfig', 'team_id')
    op.add_column('googledriveconfig', sa.Column('team_config_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'googledriveconfig', type_='foreignkey')
    op.create_foreign_key('googledriveconfig_team_config_id_fkey', 'googledriveconfig', 'teamconfig', ['team_config_id'], ['id'])
    op.drop_column('googledriveconfig', 'team_id')
    op.add_column('atlassianconfig', sa.Column('team_config_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'atlassianconfig', type_='foreignkey')
    op.create_foreign_key('atlassianconfig_team_config_id_fkey', 'atlassianconfig', 'teamconfig', ['team_config_id'], ['id'])
    op.drop_column('atlassianconfig', 'team_id')
    op.create_table('teamconfig',
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name='teamconfig_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='teamconfig_pkey')
    )
    # ### end Alembic commands ###
